import { NOTES, type Note } from './data';

export const STORAGE_KEY = 'yebian.demo.v2';
export const LEGACY_STORAGE_KEY = 'yebian.demo.v1';
export const MAX_CHARS = 100;
export const MAX_NOTE_CHARS = 200;
export const MAX_MESSAGE_CHARS = 200;
export const countChars = (text: string) => Array.from(text).length;
export const clampText = (text: string, max = MAX_CHARS) => Array.from(text).slice(0, max).join('');
export const escapeHtml = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export const localDay = (date = new Date()) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
export const safetyTerms = ['自杀', '自残', '不想活', '不想再活', '想死', '结束生命', '结束自己的生命', '伤害自己', '割腕', '跳楼', '轻生', '活不下去', '杀死自己', 'suicide', 'kill myself'];
export const hasSafetyRisk = (text: string) => safetyTerms.some(word => text.toLowerCase().replace(/\s/g, '').includes(word.replace(/\s/g, '')));
export interface Match { note: Note; hits: string[]; score: number; reason: string }
export function matchNotes(text: string): Match[] { return NOTES.map(note => { const hits = note.words.filter(word => text.includes(word)); return { note, hits, score: hits.length, reason: hits.length ? `你写下的「${hits.join('」「')}」与这张纸条有文字上的交集，因此先翻到了这一页。` : '这张纸条与你的这句话没有直接交集，供你自由翻阅。' }; }).sort((a, b) => b.score - a.score); }
export interface Entry { id: string; noteId: string; text: string; day: string; createdAt: string; reply: string | null; replyDraft: string; repliedAt: string | null }
export type MessageKind = 'text' | 'image' | 'drawing';
export interface Message { id: string; conversationId: string; sender: 'me' | 'reader'; kind: MessageKind; text: string; image?: string; drawing?: number; createdAt: string; read: boolean }
export interface Conversation { id: string; entryId: string; readerName: string; portrait: string; createdAt: string; messages: Message[] }
export interface Session { text: string; skipped: string[] }
export interface State { version: 2; reader: string; joinedAt: string; draft: string; portrait: string | null; portraitTemplates: string[]; entries: Entry[]; session: Session | null; conversations: Conversation[]; updatedAt: number; undoKey: string; volume: number }
export function newState(): State { return { version: 2, reader: String(Math.floor(Math.random() * 900000) + 100000), joinedAt: new Date().toISOString(), draft: '', portrait: null, portraitTemplates: [], entries: [], session: null, conversations: [], updatedAt: Date.now(), undoKey: 'ctrl+z', volume: 0.5 }; }
const record = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const text = (v: unknown, max = 100): v is string => typeof v === 'string' && countChars(v) <= max;
const iso = (v: unknown): v is string => typeof v === 'string' && Number.isFinite(Date.parse(v));
const day = (v: unknown): v is string => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v) && localDay(new Date(`${v}T12:00:00`)) === v;
const noteId = (v: unknown): v is string => NOTES.some(n => n.id === v);
const image = (v: unknown): v is string => typeof v === 'string' && v.length <= 1000000 && /^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v);
export const isPortraitTemplate = (v: unknown): v is string => typeof v === 'string' && v.length < 1500000 && /^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(v);
export function parseState(raw: string): State | null { try { const s: unknown = JSON.parse(raw); if (!record(s) || s.version !== 2 || typeof s.reader !== 'string' || !/^\d{6}$/.test(s.reader) || !iso(s.joinedAt) || !text(s.draft, MAX_NOTE_CHARS) || typeof s.updatedAt !== 'number' || !Number.isFinite(s.updatedAt) || !(s.portrait === null || (typeof s.portrait === 'string' && s.portrait.length < 1500000 && (/^preset:[0-5]$/.test(s.portrait) || /^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(s.portrait))))) return null; if (!Array.isArray(s.entries) || s.entries.length > 10000 || !Array.isArray(s.conversations) || s.conversations.length > 10000) return null; const ids = new Set<string>(); for (const e of s.entries) { if (!record(e) || typeof e.id !== 'string' || !/^[a-zA-Z0-9-]{1,80}$/.test(e.id) || !noteId(e.noteId) || !text(e.text, MAX_NOTE_CHARS) || !e.text.trim() || !day(e.day) || !iso(e.createdAt) || !text(e.replyDraft, MAX_NOTE_CHARS) || !(e.reply === null || (text(e.reply, MAX_NOTE_CHARS) && !!e.reply.trim())) || !(e.repliedAt === null || iso(e.repliedAt)) || ((e.reply === null) !== (e.repliedAt === null)) || ids.has(e.id)) return null; ids.add(e.id); } for (const c of s.conversations) { if (!record(c) || typeof c.id !== 'string' || typeof c.entryId !== 'string' || typeof c.readerName !== 'string' || !text(c.readerName, 100) || typeof c.portrait !== 'string' || !(/^preset:[0-5]$/.test(c.portrait) || /^data:image\/png;base64,/.test(c.portrait)) || !iso(c.createdAt) || !Array.isArray(c.messages)) return null; for (const m of c.messages) if (!record(m) || typeof m.id !== 'string' || m.conversationId !== c.id || !['me','reader'].includes(m.sender as string) || !['text','image','drawing'].includes(m.kind as string) || !text(m.text, MAX_MESSAGE_CHARS) || (m.image !== undefined && !image(m.image)) || (m.drawing !== undefined && (typeof m.drawing !== 'number' || !Number.isInteger(m.drawing) || m.drawing < 0 || m.drawing > 5)) || !iso(m.createdAt) || typeof m.read !== 'boolean' || (m.kind === 'image' && !m.image) || (m.kind === 'drawing' && m.drawing === undefined)) return null; } if (s.session !== null && (!record(s.session) || !text(s.session.text, MAX_NOTE_CHARS) || !s.session.text.trim() || !Array.isArray(s.session.skipped) || s.session.skipped.length > NOTES.length || !s.session.skipped.every(noteId) || new Set(s.session.skipped).size !== s.session.skipped.length)) return null; if (s.portraitTemplates === undefined) s.portraitTemplates = []; if (!Array.isArray(s.portraitTemplates) || s.portraitTemplates.length > 3 || !s.portraitTemplates.every(isPortraitTemplate)) return null; if (typeof s.undoKey !== 'string' || !/^((ctrl|shift|alt)\+){0,2}([a-z0-9]|f[1-9][0-9]?|arrow(up|down|left|right)|backspace|delete|space|enter)$/.test(s.undoKey)) s.undoKey = 'ctrl+z'; if (typeof s.volume !== 'number' || !Number.isFinite(s.volume) || s.volume < 0 || s.volume > 1) s.volume = 0.5; return s as unknown as State; } catch { return null; } }
export function migrateState(raw: string): State | null { try { const old = JSON.parse(raw); if (!record(old) || old.version !== 1) return null; const next = { ...old, version: 2, conversations: [] }; return parseState(JSON.stringify(next)); } catch { return null; } }
export function sendNote(s: State, id: string, now = new Date()): Entry | null { if (!s.session || !s.session.text.trim() || countChars(s.session.text) > MAX_NOTE_CHARS || !noteId(id) || hasSafetyRisk(s.session.text)) return null; const entry: Entry = { id: `${now.getTime()}-${Math.random().toString(36).slice(2, 10)}`, noteId: id, text: s.session.text, day: localDay(now), createdAt: now.toISOString(), reply: null, replyDraft: '', repliedAt: null }; s.entries.unshift(entry); return entry; }
export function replyTo(s: State, id: string, value: string, now = new Date()): boolean { const entry = s.entries.find(e => e.id === id); if (!entry || entry.reply !== null || !value.trim() || countChars(value) > MAX_NOTE_CHARS || hasSafetyRisk(value)) return false; entry.reply = value.trim(); entry.replyDraft = ''; entry.repliedAt = now.toISOString(); return true; }
export function addConversation(s: State, entry: Entry): Conversation { const note = NOTES.find(n => n.id === entry.noteId)!; const c: Conversation = { id: `conversation-${entry.id}`, entryId: entry.id, readerName: `读者 · ${note.number}`, portrait: `preset:${note.portrait}`, createdAt: new Date().toISOString(), messages: [{ id: `message-${entry.id}`, conversationId: `conversation-${entry.id}`, sender: 'reader', kind: 'text', text: note.reply, createdAt: new Date().toISOString(), read: true }] }; s.conversations.unshift(c); return c; }
export function addMessage(c: Conversation, textValue: string, imageValue?: string, drawingValue?: number, now = new Date()): Message | null { const kind: MessageKind = drawingValue !== undefined ? 'drawing' : imageValue ? 'image' : 'text'; if ((!textValue.trim() && !imageValue && drawingValue === undefined) || countChars(textValue) > MAX_MESSAGE_CHARS || hasSafetyRisk(textValue) || (imageValue !== undefined && !image(imageValue)) || (drawingValue !== undefined && (typeof drawingValue !== 'number' || !Number.isInteger(drawingValue) || drawingValue < 0 || drawingValue > 5))) return null; const m: Message = { id: `message-${now.getTime()}-${Math.random().toString(36).slice(2,7)}`, conversationId: c.id, sender: 'me', kind, text: textValue, ...(imageValue ? { image: imageValue } : {}), ...(drawingValue !== undefined ? { drawing: drawingValue } : {}), createdAt: now.toISOString(), read: true }; c.messages.push(m); return m; }
export class Store { state: State; warning = ''; private storage: Storage | null; constructor(storage: Storage | null) { this.storage = storage; this.state = newState(); if (!storage) { this.warning = '本地存储不可用；内容暂存在本页，关闭或刷新会丢失。'; return; } try { const raw = storage.getItem(STORAGE_KEY); const legacy = storage.getItem(LEGACY_STORAGE_KEY); const parsed = raw ? parseState(raw) : (legacy ? migrateState(legacy) : null); if (parsed) { this.state = parsed; if (!raw && legacy) storage.setItem(STORAGE_KEY, JSON.stringify(parsed)); } else if (raw || legacy) this.warning = '已忽略损坏或不兼容的本地记录。'; } catch { this.disable(); } } private disable() { this.storage = null; this.warning = '无法写入或读取本地存储；已切换本页内存模式，关闭或刷新会丢失新内容。'; } save() { this.state.updatedAt = Date.now(); try { const raw = this.storage?.getItem(STORAGE_KEY); const persisted = raw ? parseState(raw) : null; if (persisted && persisted.reader === this.state.reader) { for (const entry of persisted.entries) { const current = this.state.entries.find(e => e.id === entry.id); if (!current) this.state.entries.push(entry); else if (current.reply === null && entry.reply !== null) Object.assign(current, entry); } for (const c of persisted.conversations) if (!this.state.conversations.some(x => x.id === c.id)) this.state.conversations.push(c); } this.storage?.setItem(STORAGE_KEY, JSON.stringify(this.state)); } catch { this.disable(); } } refresh() { try { const raw = this.storage?.getItem(STORAGE_KEY); if (raw) { const next = parseState(raw); if (next) this.state = next; } } catch { this.disable(); } } accept(raw: string | null) { if (raw === null) { this.state = newState(); return true; } const next = parseState(raw); if (!next) return false; this.state = next; return true; } reset() { try { this.storage?.removeItem(STORAGE_KEY); this.storage?.removeItem(LEGACY_STORAGE_KEY); } catch { this.disable(); } this.state = newState(); } }
